version: '3'
services:
  app:
    container_name: users_api
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      NODE_ENV: production
      TZ: America/Sao_Paulo
      DB_USERNAME: app
      DB_PASSWORD: app
      DB_NAME: magazine
      ELASTICSEARCH_HOST: 'elasticsearch'
      ELASTICSEARCH_PORT: 9200
      MYSQL_PORT: 3306
      MYSQL_HOST: 'db'
      APP_NAME: 'magazine'
      APP_PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
      - db
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: Nã0S3i
        MYSQL_DATABASE: magazine
        MYSQL_USER: app
        MYSQL_PASSWORD: app
        TZ: America/Sao_Paulo
  adminer:    
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    container_name: elastic
    environment:
      - cluster.name=docker-cluster
      #- bootstrap.memory_lock=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - TZ=America/Sao_Paulo
    ports:
      - "9200:9200"
      - "9300:9300"